env:
  browser: true
extends:
  - 'plugin:react/recommended'
  - google
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 11
  sourceType: module
plugins:
  - react
rules: {
  "react/prop-types": 0,
  "max-len": [2, 100, 4, {"ignoreUrls": true}],
  "object-curly-spacing": ["error", "always"]
}
