env:
  browser: true
extends:
  - 'plugin:react/recommended'
  - google
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 11
  sourceType: module
plugins:
  - react
rules: {
  "react/prop-types": 0,
  "react/display-name": 0,
  "linebreak-style": ["error", "windows"],
  "max-len": [2, 100, 4, {"ignoreUrls": true}],
  "object-curly-spacing": ["error", "always"],
  "require-jsdoc": ["error", {
    "require": {
      "FunctionDeclaration": false,
      "MethodDefinition": false,
      "ClassDeclaration": false,
      "ArrowFunctionExpression": false,
      "FunctionExpression": false
    }
  }]
}
