/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.
import config from './config';

const awsmobile = {
    "aws_project_region": config.cognito.REGION,
    "aws_cognito_identity_pool_id": config.cognito.IDENTITY_POOL_ID,
    "aws_cognito_region": config.cognito.REGION,
    "aws_user_pools_id": config.cognito.USER_POOL_ID,
    "aws_user_pools_web_client_id": config.cognito.APP_CLIENT_ID,
    "oauth": {},
    "aws_user_files_s3_bucket": "porngenomeimages190606-dev",
    "aws_user_files_s3_bucket_region": config.s3.REGION
};


export default awsmobile;
